### ISSUE TITLE
First Code Review

### ISSUE THREAD

**Issue by elmejdki** [nriqu322/Youtube-videoplayer#2]
Team Feedback:
  - you need to configure your git so your profile is linked,
  - commit a little bit often,
  - add a brief introduction on the readme file,
  - good job with using semantic HTML,
  - try to use the 2 spaces instead of the tab cause it is more recommended,
  - Good comments on your HTML file,
  - you have a clean html and css files,
  - you need to add some comments on the css file,
  - instead of div elements use section for the two big sections,
  - use percentages in between your video section and the suggested video section.

**Comment by nriqu322** [comment]
Recommendations accepted and applied. thanks!
