### ISSUE TITLE
Team 79 comentaries

### ISSUE THREAD

**Issue by carlosprietobarron** [nriqu322/Youtube-videoplayer#3]
I think you did a really good job congrats, my only suggestion is from the requirements "It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar."
In the archive they gave us to replicate they don't have these 3 images but in the updated version of youtube that we use today you can use some of those icons/buttons

"It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar." 

on the sign in button use a button tag <button> </button> instead of the <a></a> tag

Use IDs instead of Class tag on the individual elements that will hold specific logic in the project

**Comment by nriqu322** [comment]
All fixed
